const books = [
    {
        
        id: 1, 
        tittle: "Os Inovadores - Uma Biografia da Revolução Digital", 
        genre: "Biography", 
        author: "Walter Isaacson", 
        pages: 568, 
        publication: "Publicado em 07 de Outubro de 2014", 
    },
    {
        id: 2, 
        tittle: "The Everything Store: Jeff Bezos and the Age of Amazon", 
        genre: "Biography", 
        author: "Brad Stone", 
        pages: 388, 
        publication: "Publicado em 2013", 
    }, 
    {
        id: 3, 
        tittle: "Benjamin Franklin. Uma Vida Americana", 
        genre: "Biography", 
        author: "Walter Isaacson", 
        pages: 672, 
        publication: "Publicado em 2003", 
    }, 
    {
        id: 4, 
        tittle: "Steve Jobs", 
        genre: "Biography", 
        author: "Walter Isaacson", 
        pages: 710, 
        publication: "Publicado em 24 de Outubro de 2011", 
    }, 
    {
        id: 5,
        tittle: "Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future", 
        genre: "Biography", 
        author: "Ashlee Vance", 
        pages: 399, 
        publication: "Publicado em 19 de Maio de 2015", 
    }, 
    {
        id: 6, 
        tittle: "Os Assassinatos da Rua Morgue", 
        genre: "Mystery", 
        author: "Edgar Allan Poe", 
        pages: 255, 
        publication: "Publicado em Abril de 1841",
    }, 
    {
        id: 7, 
        tittle: "O Assassinato de Roger Ackroyd", 
        genre: "Mystery", 
        author: "Agatha Christie", 
        pages: 263, 
        publication: "Publicado em Junho de 1926", 
    }, 
    {
        id: 8, 
        tittle: "Boneco de Neve", 
        genre: "Mystery", 
        author: "Jo Nesbø", 
        pages: 566, 
        publication: "Publicado em 2007", 
    }, 
    {
        id: 9, 
        tittle: "Arsène Lupin: Ladrão de Casaca", 
        genre: "Mystery", 
        author: "Maurice Leblanc", 
        pages:  294, 
        publication: "Publicado em 10 de Junho de 1907", 
    }, 
    {
        id: 10,
        tittle: "Mr. Mercedes", 
        genre: "Mystery", 
        author: "Stephen King", 
        pages: 418, 
        publication: "Publicado em 3 de Junho de 2014", 
    }, 
    {
        id: 11, 
        tittle: "Frankenstein", 
        genre: "Horror", 
        author: "Mary Shelley", 
        pages: 193, 
        publication: "Publicado em 1823", 
    }, 
    {
        id: 12, 
        tittle: "O Chamado de Cthulhu", 
        genre: "Horror", 
        author: "H. P. Lovecraft", 
        pages: 284, 
        publication: "Publicado em Fevereiro de 1928", 
    }, 
    {
        id: 13, 
        tittle: "Histórias Extraordinárias", 
        genre: "Horror", 
        author: "Edgar Allan Poe", 
        pages: 377, 
        publication: "Publicado em 15 de Fevereiro de 1845", 
    }, 
    {
        id: 14, 
        tittle: "A Assombração da Casa da Colina", 
        genre: "Horror", 
        author: "Shirley Jackson", 
        pages: 201, 
        publication: "Publicado em 1959", 
    }, 
    {
        id: 15, 
        tittle: "Evangelho de Sangue", 
        genre: "Horror", 
        author: "Clive Barker", 
        pages: 355, 
        publication: "Publicado em 19 de Maio de 2015", 
    }, 
    {
        id: 16, 
        tittle: "O Senhor dos Anéis: A Sociedade do Anel", 
        genre: "Fantasy", 
        author: "J. R. R. Tolkien", 
        pages: 609, 
        publication: "Publicado em 29 de Julho de 1954", 
    }, 
    {
        id: 17, 
        tittle: "A Guerra dos Tronos - As Crônicas de Gelo e Fogo I", 
        genre: "Fantasy", 
        author: "George R. R. Martin", 
        pages: 1137, 
        publication: "Publicado em 25 de Março de 2019", 
    }, 
    {
        id: 18, 
        tittle: "Miss Peregrine's Home for Peculiar Children I", 
        genre: "Fantasy", 
        author: "Ransom Riggs", 
        pages: 358, 
        publication: "Publicado em 7 de Junho de 2011", 
    }, 
    {
        id: 19, 
        tittle: "Alice no País das Maravilhas", 
        genre: "Fantasy", 
        author: "Lewis Carroll", 
        pages: 172, 
        publication: "Publicado em 1 de Novembro de 1998", 
    }, 
    {
        id: 20, 
        tittle: "As Brumas de Avalon - Ciclo de Avalon I", 
        genre: "Fantasy", 
        author: "Marion Zimmer Bradley", 
        pages: 1487, 
        publication: "Publicado em 23 de Outubro de 2017",
    }
]

module.exports = books
